### ISSUE TITLE
Dates on Calendar

### ISSUE THREAD

**Issue by Sajid13** [KrisnelC/townsville-app-issues#4]
Hey guys, 
The dates go from the 2nd of July to the 9th of July. It is currently the 1st of July to the 8th of July

**Comment by Sajid13** [comment]
And the other ones arent in yet, so I assume that it is yet to be completed ;D

**Comment by Sajid13** [comment]
Any comments on posts come up as Hello O.o instead of the comment I write?

**Comment by honormagon** [comment]
Comment thing occurs to me too

**Comment by krisnelc** [comment]
Ahhhh! Sorry guys that's been fixed in the build I'll push out asap.

**Comment by honormagon** [comment]
Via Academic tab > Monday, Wednesday, Thursday > linked to incorrect day with "fake" event

**Comment by krisnelc** [comment]
Do you mean that clicking on those days in the academic tab will take you to "Monday" on the calendar page?

**Comment by honormagon** [comment]
Oh, no it does. It links to each of their individual days. I just didn't notice as they hadn't been populated yet. My bad!

**Comment by krisnelc** [comment]
I'll add a loading icon for you Honor.
